server:
  port: 8080

spring:
  application:
    name: kafka
  kafka:
    bootstrap-servers: 192.168.124.128:9092 # kafka????
    producer: # ?????
      retries: 3 # ????0????????????????????
      batch-size: 16384 #16K
      buffer-memory: 33554432 #32M
      acks: 1
      # ????key??????????
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: zhTestGroup # ????
      enable-auto-commit: false # ??????
      auto-offset-reset: latest # ??????????offset??????offset?????????offset????????
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: com.topsec.portal.kafkaspringboottest.config.AvroDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    listener:
      # ??????????????ListenerConsumer???????
      # RECORD
      # ????poll()???????????ListenerConsumer???????
      # BATCH
      # ????poll()???????????ListenerConsumer????????????????TIME???
      # TIME
      # ????poll()???????????ListenerConsumer?????????record??????COUNT???
      # COUNT
      # TIME |?COUNT???????????
      # COUNT_TIME
      # ????poll()???????????ListenerConsumer?????, ????Acknowledgment.acknowledge()???
      # MANUAL
      # ????Acknowledgment.acknowledge()????????????
      # MANUAL_IMMEDIATE
      ack-mode: manual_immediate